services:
  web:
    build: web
    image: smithmicro/n7m-web
    restart: always
    depends_on:
      - api
      - ui
    mem_limit: 100m
  ui:
    build: ui
    image: smithmicro/n7m-ui
    restart: always
    mem_limit: 100m
  api:
    build: api
    image: smithmicro/n7m-api
    restart: always
    environment:
      - WEB_CONCURRENCY=2
    depends_on:
      - gis
    mem_limit: 200m
  feed:
    build: feed
    image: smithmicro/n7m-feed
    depends_on:
      - gis
    environment:
      - OSM_FILENAME=planet-latest.osm.pbf
      - NOMINATIM_REPLICATION_URL=https://planet.openstreetmap.org/replication/day/
      - NOMINATIM_REPLICATION_MAX_DIFF=3000
      - NOMINATIM_REPLICATION_UPDATE_INTERVAL=86400
    volumes:
      - n7m_feed_data:/data/
  gis:
    build: gis
    image: smithmicro/n7m-gis
    restart: always
    volumes:
      - n7m_pg_data:/var/lib/postgresql/data
  bastion:
    image: debian:bookworm
    volumes:
      - n7m_feed_data:/data/
volumes:
  n7m_pg_data:
      external: false
  n7m_feed_data:
    external: false