version: '2'

services:
  web:
    build: web
    image: smithmicro/n7m-web
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - app
      - ui
    mem_limit: 100m
  ui:
    build: ui
    image: smithmicro/n7m-ui
    restart: always
    depends_on:
      - app
    mem_limit: 100m
  app:
    build: app
    image: smithmicro/n7m-app
    #restart: always
    environment:
      - PGPASSWORD=n7m-geocoding
    depends_on:
      - gis
    mem_limit: 200m
  feed:
    image: smithmicro/n7m-app
    depends_on:
      - gis
    environment:
      - PGPASSWORD=n7m-geocoding
      - OSM_FILENAME=monaco-latest.osm.pbf
    command: setup
    volumes:
      - ${PWD}/data:/data/
  test:
    build: test
    image: smithmicro/n7m-test
    environment:
      - PGPASSWORD=n7m-geocoding
    depends_on:
      - gis
    mem_limit: 200m
    command: "true"
  gis:
    build: gis
    image: smithmicro/n7m-gis
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=n7m-geocoding
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
