services:
  web:
    image: smithmicro/n7m-web
    restart: always
    ports:
      - "80:80"
    depends_on:
      - app
      - ui
    mem_limit: 100m
  ui:
    image: smithmicro/n7m-ui
    restart: always
    mem_limit: 100m
  app:
    image: smithmicro/n7m-app
    restart: always
    depends_on:
      - gis
    environment:
      - PGPASSWORD=n7m-geocoding
      - WEB_CONCURRENCY=4
  gis:
    image: smithmicro/n7m-gis:15
    restart: always
    environment:
      - POSTGRES_PASSWORD=n7m-geocoding
    volumes:
      - /data/pgdata:/var/lib/postgresql/data
